
all:
	#gcc -otestpm testpm.c -I ../logger -I../include -I ../pm -L../logger/ -llogger -L../pm -lpm  -g -DDEBUG 
	#gcc -otestlog testlog.c -I ../logger -I../include -I ../pm -L../logger/ -llogger   -g -DDEBUG
	#gcc -otestccr testccr.c -I ../logger -I../include -I ../ccr -L../logger/ -llogger -L../ccr -lccr  -g -DDEBUG
	gcc -otestdio testdio.c -I ../logger -I ../include -I../dio -L../logger/ -llogger -L../dio -ldio  -g -DDEBUG


